package com.tomtresansky.gradle.plugin.schemaspy

import org.gradle.api.DomainObjectCollection
import org.gradle.api.reporting.DirectoryReport
import org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport

/**
 * The set of reports that can be generated by the {@link SchemaSpyReportTask} task type.
 * <p>
 * Note: can't extends <code>ReportContainer&lt;TaskGeneratedSingleDirectoryReport&gt;</code> here, because it leads to:
 * <pre>
 * Could not compile build file 'C:\Users\Tom\Programming\Projects\DuelMaster\build.gradle'.
 * > startup failed:
 *  build file 'C:\Users\Tom\Programming\Projects\DuelMaster\build.gradle': -1: The return type of org.gradle.api.NamedDomainObjectCollection matching(groovy.lang.Closure) in org.gradle.api.internal.DefaultNamedDomainObjectCollection is incompatible with org.gradle.api.NamedDomainObjectSet in org.gradle.api.NamedDomainObjectSet
 *  . At [-1:-1]  @ line -1, column -1.
 * </pre>
 * Maybe a newer version of Gradle will fix it?  {@link DomainObjectCollection} seems to work.  Anything above it in the hierarchy, even {@link NamedDomainObjectCollection}, doesn't.
 
 * @author Tom
 */
interface SchemaSpyReportContainer extends DomainObjectCollection<TaskGeneratedSingleDirectoryReport> { // TODO: fix this extends?  
  /**
   * The SchemaSpy HTML report.
   *
   * @return the SchemaSpy HTML report
   */
  DirectoryReport getHtml()
}
