package com.tomtresansky.gradle.plugin.schemaspy;

import org.gradle.api.reporting.DirectoryReport;
import org.gradle.api.reporting.ReportContainer;
import org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport;

/**
 * The set of reports that can be generated by the {@link SchemaSpyReportTask}
 * task type.
 * <p>
 * This class <strong>MUST be a java class</strong> or else this project will
 * <strong>NOT</strong> compile under gradle. See <a href=
 * "https://discuss.gradle.org/t/incompatible-return-type-error-when-using-reportcontainer-and-taskreportcontainer/1735"
 * >this thread in the gradle forums</a> and <a
 * href="https://jira.codehaus.org/browse/GROOVY-5418">this groovy issue</a> for
 * more information.
 *
 * @author Tom
 */
public interface SchemaSpyReportContainer extends
ReportContainer<TaskGeneratedSingleDirectoryReport> {
  /**
   * The SchemaSpy HTML report.
   *
   * @return the SchemaSpy HTML report
   */
  DirectoryReport getHtml();
}
